name: psych
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - jupyter=1.1.1
  - libcblas=3.9.0
  - notebook=7.2.2
  - matplotlib=3.9.2
  - numpy=1.26.4
  - openblas=0.3.21
  - pandas=2.2.2
  - pytest=8.3.3
  - python=3.12.6
  - scikit-learn=1.5.2